version: '3.6'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/backend
    entrypoint: >
      /bin/sh -c '
        mysql -h database -u root -p${MYSQL_ROOT_PASSWORD} -e "DROP DATABASE IF EXISTS \`tic-tac-toe\`; CREATE DATABASE \`tic-tac-toe\`; show databases;";
        java -jar ./backend/tic-tac-toe.jar --spring.datasource.url=jdbc:mysql://database:3306/tic-tac-toe --spring.datasource.username=root --spring.datasource.password=${MYSQL_ROOT_PASSWORD}
      '
    networks:
      - services-network

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
      - 33060:33060
    healthcheck:
      test: 'mysql -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} -e "show databases;";'
      timeout: 10s
      interval: 1s
      retries: 10
    networks:
      - services-network

networks:
  services-network:
    driver: bridge